In [1]:
pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 36.7 MB/s 
     |████████████████████████████████| 7.6 MB 58.3 MB/s 
     |████████████████████████████████| 182 kB 78.0 MB/s 


In [2]:
import pandas as pd

In [3]:
pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 452 kB 30.0 MB/s 
     |████████████████████████████████| 213 kB 28.5 MB/s 
     |████████████████████████████████| 132 kB 78.4 MB/s 
     |████████████████████████████████| 127 kB 81.9 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [4]:
from datasets import load_dataset

raw_datasets = load_dataset("SetFit/sst5")
raw_datasets

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/SetFit___json/SetFit--sst5-4c07b9d5881ae209/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 8544
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2210
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 1101
    })
})

In [5]:
raw_datasets

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 8544
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2210
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 1101
    })
})

In [6]:
raw_datasets['train']

Dataset({
    features: ['text', 'label', 'label_text'],
    num_rows: 8544
})

In [7]:
# unique labels
set(raw_datasets['train']['label'])

{0, 1, 2, 3, 4}

In [8]:
raw_datasets['train'].features

{'text': Value(dtype='string', id=None),
 'label': Value(dtype='int64', id=None),
 'label_text': Value(dtype='string', id=None)}

In [9]:
from transformers import AutoTokenizer

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenized_text = tokenizer(raw_datasets["train"]["text"])

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [10]:
tokenized_dataset = tokenizer(
    raw_datasets["train"]["text"],
    padding=True,
    truncation=True,
)

In [11]:
def tokenize_function(example):
    return tokenizer(example["text"], example["label_text"],truncation=True)

In [12]:
tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
tokenized_datasets

  0%|          | 0/9 [00:00<?, ?ba/s]

  0%|          | 0/3 [00:00<?, ?ba/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 8544
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2210
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1101
    })
})

In [13]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")

In [14]:
samples = tokenized_datasets["train"][:8]

In [15]:
samples = {k: v for k, v in samples.items() if k not in ["text", "label_text"]}

In [16]:
samples

{'label': [4, 1, 1, 2, 3, 2, 3, 3],
 'input_ids': [[101,
   1037,
   18385,
   1010,
   6057,
   1998,
   2633,
   18276,
   2128,
   1011,
   16603,
   1997,
   5053,
   1998,
   1996,
   6841,
   1998,
   5687,
   5469,
   3152,
   102,
   2200,
   3893,
   102],
  [101,
   4593,
   2128,
   27241,
   23931,
   2013,
   1996,
   6276,
   1011,
   2282,
   2723,
   1997,
   2151,
   2445,
   12217,
   7815,
   1012,
   102,
   4997,
   102],
  [101,
   2027,
   3653,
   23545,
   2037,
   4378,
   24185,
   1050,
   1005,
   1056,
   4133,
   2145,
   2005,
   1037,
   11507,
   10800,
   1010,
   2174,
   14036,
   2135,
   3591,
   1010,
   2061,
   2027,
   19817,
   4140,
   2041,
   1996,
   7511,
   2671,
   1011,
   4349,
   3787,
   1997,
   11829,
   1011,
   7168,
   9219,
   1998,
   28971,
   2308,
   1999,
   8301,
   8737,
   2100,
   4253,
   1012,
   102,
   4997,
   102],
  [101,
   1996,
   2972,
   3185,
   2003,
   3561,
   2007,
   2139,
   3900,
   24728,
   5312

In [17]:
[len(x) for x in samples["input_ids"]]

[24, 20, 50, 15, 25, 9, 32, 26]

In [18]:
batch = data_collator(samples)
{k: v.shape for k, v in batch.items()}

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


{'input_ids': TensorShape([8, 50]),
 'token_type_ids': TensorShape([8, 50]),
 'attention_mask': TensorShape([8, 50]),
 'labels': TensorShape([8])}

In [19]:
tokenized_datasets["train"].features

{'text': Value(dtype='string', id=None),
 'label': Value(dtype='int64', id=None),
 'label_text': Value(dtype='string', id=None),
 'input_ids': Sequence(feature=Value(dtype='int32', id=None), length=-1, id=None),
 'token_type_ids': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None),
 'attention_mask': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None)}

In [20]:
tf_train_dataset = tokenized_datasets["train"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=True,
    collate_fn=data_collator,
    batch_size=8,
)

tf_validation_dataset = tokenized_datasets["validation"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=False,
    collate_fn=data_collator,
    batch_size=8,
)

tf_test_dataset = tokenized_datasets["test"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=False,
    collate_fn=data_collator,
    batch_size=8,
)

### Fine-tuning a model with Keras

In [21]:
from transformers import TFAutoModelForSequenceClassification

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=5)

Downloading:   0%|          | 0.00/536M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [22]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

model.compile(
    optimizer="adam",
    loss=SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)
model.fit(
    tf_train_dataset,
    validation_data=tf_validation_dataset,
)

1068/1068 [==============================] - 164s 123ms/step - loss: 1.5999 - accuracy: 0.2599 - val_loss: 1.6114 - val_accuracy: 0.2534


In [23]:
from tensorflow.keras.optimizers.schedules import PolynomialDecay

batch_size = 8
num_epochs = 3
# The number of training steps is the number of samples in the dataset, divided by the batch size then multiplied
# by the total number of epochs. Note that the tf_train_dataset here is a batched tf.data.Dataset,
# not the original Hugging Face Dataset, so its len() is already num_samples // batch_size.
num_train_steps = len(tf_train_dataset) * num_epochs
lr_scheduler = PolynomialDecay(
    initial_learning_rate=5e-5, end_learning_rate=0.0, decay_steps=num_train_steps
)
from tensorflow.keras.optimizers import Adam

opt = Adam(learning_rate=lr_scheduler)

In [24]:
import tensorflow as tf

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer=opt, loss=loss, metrics=["accuracy"])

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [25]:
model.fit(tf_train_dataset, validation_data=tf_validation_dataset, epochs=3)

Epoch 1/3
1068/1068 [==============================] - 153s 128ms/step - loss: 0.0430 - accuracy: 0.9908 - val_loss: 8.1056e-04 - val_accuracy: 1.0000
Epoch 2/3
1068/1068 [==============================] - 126s 118ms/step - loss: 7.3292e-04 - accuracy: 1.0000 - val_loss: 3.7286e-04 - val_accuracy: 1.0000
Epoch 3/3
1068/1068 [==============================] - 126s 118ms/step - loss: 4.3222e-04 - accuracy: 1.0000 - val_loss: 2.9046e-04 - val_accuracy: 1.0000


In [27]:
import numpy as np

In [26]:
preds = model.predict(tf_validation_dataset)["logits"]

138/138 [==============================] - 8s 42ms/step


In [31]:
probabilities = tf.nn.softmax(preds)

In [32]:
np.argmax(probabilities, axis=1)

array([2, 1, 1, ..., 0, 3, 4])

In [28]:
class_preds = np.argmax(preds, axis=1)
print(preds.shape, class_preds.shape)

(1101, 5) (1101,)


In [36]:
probabilities

<tf.Tensor: shape=(1101, 5), dtype=float32, numpy=
array([[1.08000611e-04, 1.34413800e-04, 9.99561965e-01, 1.02806844e-04,
        9.28005975e-05],
       [6.56530974e-05, 9.99764264e-01, 5.68342875e-05, 5.57408057e-05,
        5.74321093e-05],
       [5.81352215e-05, 9.99763668e-01, 5.93614968e-05, 5.82327739e-05,
        6.05189052e-05],
       ...,
       [9.99686480e-01, 7.77593377e-05, 8.64476024e-05, 6.64774707e-05,
        8.29911223e-05],
       [4.11190485e-05, 5.21994152e-05, 6.46303888e-05, 9.99786437e-01,
        5.56316336e-05],
       [7.08551015e-05, 7.85297307e-05, 7.45814759e-05, 6.99574521e-05,
        9.99706089e-01]], dtype=float32)>